package blog.anirbanm.query.model.am;

import blog.anirbanm.query.model.am.common.QueryModule;
import blog.anirbanm.query.model.vo.EmployeesVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 04 19:08:11 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class QueryModuleImpl extends ApplicationModuleImpl implements QueryModule {
    /**
     * This is the default constructor (do not remove).
     */
    public QueryModuleImpl() {
    }
    
    public void searchWrongWay(final String firstName, final String lastName) {
        System.out.println("Searching with first_name = " + firstName + " and last_name = " + lastName);
        final EmployeesVOImpl empView = getEmployeesVO1();
        empView.setWhereClause(" FIRST_NAME = '" + firstName + "' AND LAST_NAME = '" + lastName + "'");
        empView.setRangeSize(-1);
        empView.executeQuery();
    }
    
    public void searchRightWay(final String firstName, final String lastName) {
        System.out.println("Searching with first_name = " + firstName + " and last_name = " + lastName);
        final EmployeesVOImpl empView = getEmployeesVO1();
        
        empView.setWhereClause(" FIRST_NAME = :1 AND LAST_NAME = :2 ");
        empView.setWhereClauseParam(0, firstName);
        empView.setWhereClauseParam(1, lastName);
        empView.setRangeSize(-1);
        empView.executeQuery();
        
        empView.setWhereClauseParams(null); // this is very important
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public EmployeesVOImpl getEmployeesVO1() {
        return (EmployeesVOImpl) findViewObject("EmployeesVO1");
    }
}

